project:
  type: book

book:
  title: "Data Science for Resident"
  author: "Kittipos Sirivongrungson"
  date: "10/6/2023"
  chapters:
    - index.qmd
    - part: "Modeling"
      chapters: 
        - content/lm.qmd
    - part: "Statistics"
      chapters: 
        - content/cor.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    html-math-method: mathjax
  # pdf:
  #   documentclass: scrreprt

execute: 
  freeze: auto
  
code-fold: true

