{
  "hash": "e6ee44a90e11bdc72ed25982d7d090a6",
  "result": {
    "markdown": "---\ntitle: \"Linear Regression\"\nexecute: \n  warning: false\n---\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(palmerpenguins)\nlibrary(tidyverse)\ntheme_set(theme_bw())\n```\n:::\n\n\n## Explore Data\n\n`penguins` dataset has 344 rows x 8 columns. Here are the first 6 rows of the data.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npenguins <- na.omit(penguins) # Remove missing value of simplicity\nhead(penguins)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<table class=\"table table-striped table-hover table-responsive\" style=\"margin-left: auto; margin-right: auto;\">\n <thead>\n  <tr>\n   <th style=\"text-align:left;\"> species </th>\n   <th style=\"text-align:left;\"> island </th>\n   <th style=\"text-align:right;\"> bill_length_mm </th>\n   <th style=\"text-align:right;\"> bill_depth_mm </th>\n   <th style=\"text-align:right;\"> flipper_length_mm </th>\n   <th style=\"text-align:right;\"> body_mass_g </th>\n   <th style=\"text-align:left;\"> sex </th>\n   <th style=\"text-align:right;\"> year </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;\"> Adelie </td>\n   <td style=\"text-align:left;\"> Torgersen </td>\n   <td style=\"text-align:right;\"> 39.1 </td>\n   <td style=\"text-align:right;\"> 18.7 </td>\n   <td style=\"text-align:right;\"> 181 </td>\n   <td style=\"text-align:right;\"> 3750 </td>\n   <td style=\"text-align:left;\"> male </td>\n   <td style=\"text-align:right;\"> 2007 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Adelie </td>\n   <td style=\"text-align:left;\"> Torgersen </td>\n   <td style=\"text-align:right;\"> 39.5 </td>\n   <td style=\"text-align:right;\"> 17.4 </td>\n   <td style=\"text-align:right;\"> 186 </td>\n   <td style=\"text-align:right;\"> 3800 </td>\n   <td style=\"text-align:left;\"> female </td>\n   <td style=\"text-align:right;\"> 2007 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Adelie </td>\n   <td style=\"text-align:left;\"> Torgersen </td>\n   <td style=\"text-align:right;\"> 40.3 </td>\n   <td style=\"text-align:right;\"> 18.0 </td>\n   <td style=\"text-align:right;\"> 195 </td>\n   <td style=\"text-align:right;\"> 3250 </td>\n   <td style=\"text-align:left;\"> female </td>\n   <td style=\"text-align:right;\"> 2007 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Adelie </td>\n   <td style=\"text-align:left;\"> Torgersen </td>\n   <td style=\"text-align:right;\"> 36.7 </td>\n   <td style=\"text-align:right;\"> 19.3 </td>\n   <td style=\"text-align:right;\"> 193 </td>\n   <td style=\"text-align:right;\"> 3450 </td>\n   <td style=\"text-align:left;\"> female </td>\n   <td style=\"text-align:right;\"> 2007 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Adelie </td>\n   <td style=\"text-align:left;\"> Torgersen </td>\n   <td style=\"text-align:right;\"> 39.3 </td>\n   <td style=\"text-align:right;\"> 20.6 </td>\n   <td style=\"text-align:right;\"> 190 </td>\n   <td style=\"text-align:right;\"> 3650 </td>\n   <td style=\"text-align:left;\"> male </td>\n   <td style=\"text-align:right;\"> 2007 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Adelie </td>\n   <td style=\"text-align:left;\"> Torgersen </td>\n   <td style=\"text-align:right;\"> 38.9 </td>\n   <td style=\"text-align:right;\"> 17.8 </td>\n   <td style=\"text-align:right;\"> 181 </td>\n   <td style=\"text-align:right;\"> 3625 </td>\n   <td style=\"text-align:left;\"> female </td>\n   <td style=\"text-align:right;\"> 2007 </td>\n  </tr>\n</tbody>\n</table>\n`````\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ngtsummary::tbl_summary(penguins)\n```\n\n::: {.cell-output-display}\n```{=html}\n<div id=\"xgksjbcnyo\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#xgksjbcnyo table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#xgksjbcnyo thead, #xgksjbcnyo tbody, #xgksjbcnyo tfoot, #xgksjbcnyo tr, #xgksjbcnyo td, #xgksjbcnyo th {\n  border-style: none;\n}\n\n#xgksjbcnyo p {\n  margin: 0;\n  padding: 0;\n}\n\n#xgksjbcnyo .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#xgksjbcnyo .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#xgksjbcnyo .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#xgksjbcnyo .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#xgksjbcnyo .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#xgksjbcnyo .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#xgksjbcnyo .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#xgksjbcnyo .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#xgksjbcnyo .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#xgksjbcnyo .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#xgksjbcnyo .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#xgksjbcnyo .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#xgksjbcnyo .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#xgksjbcnyo .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#xgksjbcnyo .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#xgksjbcnyo .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#xgksjbcnyo .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#xgksjbcnyo .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#xgksjbcnyo .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#xgksjbcnyo .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#xgksjbcnyo .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#xgksjbcnyo .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#xgksjbcnyo .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#xgksjbcnyo .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#xgksjbcnyo .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#xgksjbcnyo .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#xgksjbcnyo .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#xgksjbcnyo .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#xgksjbcnyo .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#xgksjbcnyo .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#xgksjbcnyo .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#xgksjbcnyo .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#xgksjbcnyo .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#xgksjbcnyo .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#xgksjbcnyo .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#xgksjbcnyo .gt_left {\n  text-align: left;\n}\n\n#xgksjbcnyo .gt_center {\n  text-align: center;\n}\n\n#xgksjbcnyo .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#xgksjbcnyo .gt_font_normal {\n  font-weight: normal;\n}\n\n#xgksjbcnyo .gt_font_bold {\n  font-weight: bold;\n}\n\n#xgksjbcnyo .gt_font_italic {\n  font-style: italic;\n}\n\n#xgksjbcnyo .gt_super {\n  font-size: 65%;\n}\n\n#xgksjbcnyo .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#xgksjbcnyo .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#xgksjbcnyo .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#xgksjbcnyo .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#xgksjbcnyo .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#xgksjbcnyo .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#xgksjbcnyo .gt_indent_5 {\n  text-indent: 25px;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    \n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;strong&gt;Characteristic&lt;/strong&gt;\"><strong>Characteristic</strong></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;strong&gt;N = 333&lt;/strong&gt;&lt;span class=&quot;gt_footnote_marks&quot; style=&quot;white-space:nowrap;font-style:italic;font-weight:normal;&quot;&gt;&lt;sup&gt;1&lt;/sup&gt;&lt;/span&gt;\"><strong>N = 333</strong><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;\"><sup>1</sup></span></th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">species</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\"></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Adelie</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">146 (44%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Chinstrap</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">68 (20%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Gentoo</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">119 (36%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">island</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\"></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Biscoe</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">163 (49%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Dream</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">123 (37%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Torgersen</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">47 (14%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">bill_length_mm</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">44.5 (39.5, 48.6)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">bill_depth_mm</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">17.30 (15.60, 18.70)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">flipper_length_mm</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">197 (190, 213)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">body_mass_g</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">4,050 (3,550, 4,775)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">sex</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\"></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    female</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">165 (50%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    male</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">168 (50%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">year</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\"></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    2007</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">103 (31%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    2008</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">113 (34%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    2009</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">117 (35%)</td></tr>\n  </tbody>\n  \n  <tfoot class=\"gt_footnotes\">\n    <tr>\n      <td class=\"gt_footnote\" colspan=\"2\"><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;\"><sup>1</sup></span> n (%); Median (IQR)</td>\n    </tr>\n  </tfoot>\n</table>\n</div>\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nvisdat::vis_dat(penguins)\n```\n\n::: {.cell-output-display}\n![](lm_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n:::\n\n\n## Simple Linear Regression Model\n\n### Plot\n\nLet's explore a relationship between `body_mass_g` and `flipper_length_mm`. In a scatter plot ([@fig-plot-peng-scatter]), we can see that there are some kind of a linear trend.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npenguins |> \n  ggplot(aes(x = flipper_length_mm, y = body_mass_g)) +\n  geom_point(color = \"maroon\", alpha = 0.5) \n```\n\n::: {.cell-output-display}\n![Scatter plot](lm_files/figure-html/fig-plot-peng-scatter-1.png){#fig-plot-peng-scatter width=672}\n:::\n:::\n\n\n### Fit Model\n\nSimple linear regression model will be fitted to the data using:\n\n-   `body_mass_g` as a numeric outcome or dependent variable (y)\n\n-   `flipper_length_mm` as a numeric predictor or independent variable (x)\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\nlm_simple_fit <- lm(body_mass_g ~ flipper_length_mm, data = penguins)\nsummary(lm_simple_fit)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = body_mass_g ~ flipper_length_mm, data = penguins)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-1057.33  -259.79   -12.24   242.97  1293.89 \n\nCoefficients:\n                  Estimate Std. Error t value Pr(>|t|)    \n(Intercept)       -5872.09     310.29  -18.93   <2e-16 ***\nflipper_length_mm    50.15       1.54   32.56   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 393.3 on 331 degrees of freedom\nMultiple R-squared:  0.7621,\tAdjusted R-squared:  0.7614 \nF-statistic:  1060 on 1 and 331 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\n\n\n\n### Coefficient interpretation\n\nSince, the simple linear regression model (one predictor) is in the form of:\n\n$$\n\\hat{y} = \\hat{\\beta_0} + \\hat{\\beta_1}x\n$$\n\n-   $\\hat{\\beta_0}$ is the estimated intercept = -5780.8\n-   $\\hat{\\beta_1}$ is the estimated coefficient (slope) of the `flipper_length_mm` = 49.7\n\nAlso, the p-value of these coefficients is statistically significant ($p$ \\< 0.001), meaning the true value is very unlikely to be zero, so that we can include these values in the linear model equation.\n\nTherefore, the equation of this linear model that has been fitted to this data can be written as:\n\n$$\nbody \\ mass \\ [g] = -5780.8 + 49.7 (flipper \\  length \\ [mm])\n$$\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npenguins |> \n  ggplot(aes(x = flipper_length_mm, y = body_mass_g)) +\n  geom_point(color = \"maroon\", alpha = 0.5) +\n  geom_smooth(method = \"lm\")\n```\n\n::: {.cell-output-display}\n![The fitted linear model (blue line) with confidence area (grey area) of the model's coefficient.](lm_files/figure-html/fig-plot-peng-scatter-lm-1.png){#fig-plot-peng-scatter-lm width=672}\n:::\n:::\n\n\nWe can explain this equation in simple terms as\n\n-   If the flipper length increase by 1 mm, the average increased in body mass would be 0.049 kg.\n\n\n### Model Performance\n\n\n\nR-squared ($R^2$) = 0.76\n\n-   This means that 76 % of the variation in the outcome (`body_mass_g`) can be explained by the predictor (`flipper_length_mm`) using this simple linear regression model.\n\n-   How about the other 24% of the outcome? Some is due to random error which we can't control (irreducible error) and most importantly due to reducible error which can be improve by many machine learning techniques, let's improve our linear model the next section.\n\n## Multiple Linear Regression\n\nWe will consider adding another variable `sex` in the model.\n\n### Plot\n\nFirst, let's see the distribution of `body_mass_g` in each `sex` ([@fig-plot-peng-scatter-sex]). As we can see, the `sex` also influence `body_mass_g`: the male penguins are, on average, heavier than female.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npenguins |> \n  ggplot(aes(x = flipper_length_mm, y = body_mass_g, color = sex)) +\n  geom_point(alpha = 0.5) \n```\n\n::: {.cell-output-display}\n![Scatter plot of body mass (g) VS flipper length (mm) for each sex.](lm_files/figure-html/fig-plot-peng-scatter-sex-1.png){#fig-plot-peng-scatter-sex width=672}\n:::\n:::\n\n\n### Fit Model\n\nMultiple linear regression model will be fitted to the data using:\n\n-   **Outcome (y):** `body_mass_g` (numeric variable)\n\n-   **Predictors (x):**\n\n    -   `flipper_length_mm` (numeric variable)\n\n    -   `sex` (binary categorical variable) has 2 levels: male, female.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\nlm_multi_fit <- lm(body_mass_g ~ flipper_length_mm + sex, data = penguins)\nsummary(lm_multi_fit)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = body_mass_g ~ flipper_length_mm + sex, data = penguins)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-910.28 -243.89   -2.94  238.85 1067.73 \n\nCoefficients:\n                   Estimate Std. Error t value Pr(>|t|)    \n(Intercept)       -5410.300    285.798 -18.931  < 2e-16 ***\nflipper_length_mm    46.982      1.441  32.598  < 2e-16 ***\nsexmale             347.850     40.342   8.623 2.78e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 355.9 on 330 degrees of freedom\nMultiple R-squared:  0.8058,\tAdjusted R-squared:  0.8047 \nF-statistic: 684.8 on 2 and 330 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\n\n\n\n### Coefficient interpretation\n\nGeneral form of multiple linear regression model with two predictors can be written as:\n\n$$\n\\hat{y} = \\hat{\\beta_0} + \\hat{\\beta_1}x_1 + \\hat{\\beta_2}x_2\n$$\n\nWhere:\n\n-   $\\hat{\\beta_0}$ is the estimated *intercept of the female* (as baseline) = -5410.3\n-   $\\hat{\\beta_1}$ is the estimated slope of both lines = 47\n-   $\\hat{\\beta_2}$ is the estimated *vertical difference* of male relative to female = 347.9\n\nThe p-value of all of the coefficients is statistically significant ($p$ \\< 0.001).\n\nTherefore, the equation of this linear model that has been fitted to this data can be written as:\n\n$$\n  body \\ mass \\ [g] = -5410.3 + 47 (flipper \\ length \\ [mm]) + 347.9 (sex) \\left\\{\n  \\begin{array}{@{}ll@{}}\n    0, & \\text{if female} \\\\\n    1, & \\text{if male}\n  \\end{array}\\right.\n$$\n\nAs in [@fig-plot-peng-scatter-lm-sex], by including categorical predictor `sex` in the model, the single line now splits into two perpendicular lines, fitted to the male and female sex.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npenguins |> \n  ggplot(aes(x = flipper_length_mm, y = body_mass_g, color = sex)) +\n  geom_point(alpha = 0.5) +\n  geom_smooth(method = \"lm\")\n```\n\n::: {.cell-output-display}\n![Multiple linear regression of body mass (g) on flipper length (mm) and sex.](lm_files/figure-html/fig-plot-peng-scatter-lm-sex-1.png){#fig-plot-peng-scatter-lm-sex width=672}\n:::\n:::\n\n\nWe can explain this equation in simple terms as:\n\n-   If the flipper length increase by 1 mm, the average increased in body mass would be 0.047 kg, in the same penguin sex.\n\n-   Male penguin is, on average, 0.35 kg heavier than female in the same flipper length.\n\n\n### Model Performance\n\nAdjusted R-squared ($R^2$) = **0.8**, increased from the previous model using simple linear regression ($R^2$ = 0.76) \n\n-   This means that 80 % of the variation in the outcome (`body_mass_g`) can be explained by the predictors (`flipper_length_mm` and `sex`) using multiple linear regression model.\n\n\n\n",
    "supporting": [
      "lm_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}