on:
    push:
      branches: main
    pull_request:
      branches: main
    # to be able to trigger a manual build
    workflow_dispatch:
  
  
  name: Quarto Publish
  
  jobs:
    build-deploy:
      runs-on: ubuntu-latest
      steps:
        - name: Check out repository
          uses: actions/checkout@v4
          
        - name: Set up Quarto
          uses: quarto-dev/quarto-actions/setup@v2
          with:
            # To install LaTeX to build PDF book 
            tinytex: true 
            # uncomment below and fill to pin a version
            # version: 0.9.600
        
        
        - name: Publish to Netlify (and render)
          uses: quarto-dev/quarto-actions/publish@v2
          with:
            to: netlify
            NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          